from . import func
from .func import IN, OUT

functions = dict(
    add = lambda n = int, a = IN, b = IN, out = OUT : None,
    sub = lambda n = int, a = IN, b = IN, out = OUT : None,
    mul = lambda n = int, a = IN, b = IN, out = OUT : None,
    div = ('div_', lambda n = int, a = IN, b = IN, out = OUT : None),
    abs = ('abs_', lambda n = int, a = IN, out = OUT : None),
    dot = ('dot', lambda a = IN, b = IN, I = int, U = int, K = int, M = int, out = OUT : None),
    print_carray = lambda data = [float] : None,
    assign = lambda data = [float], out = OUT : None,

    roi_align_forward = lambda n = int,
        bottom_data = IN,
        spatial_scale = float,
        channels = int,
        height = int,
        width = int,
        pooled_height = int,
        pooled_width = int,
        sampling_ratio = int,
        bottom_rois = IN,
        top_data = OUT : None,

    roi_align_backward = lambda n = int,
        top_diff = IN,
        num_rois = int,
        spatial_scale = float,
        channels = int,
        height = int,
        width = int,
        pooled_height = int,
        pooled_width = int,
        sampling_ratio = int,
        bottom_diff = OUT,
        bottom_rois = OUT : None,

    softmax_forward = lambda data = IN,
        num_classes = int,
        outer_size = int,
        inner_size = int,
        probs = OUT : None,

    softmax_loss_forward = lambda probs = IN,
        labels = IN,
        num_classes = int,
        outer_size = int,
        inner_size = int,
        losses = OUT : None,

    softmax_loss_backward = lambda probs = IN,
        labels = IN,
        num_classes = int,
        outer_size = int,
        inner_size = int,
        grad_scale = float,
        dX = OUT : None,
)
func.bind(functions)
